CREATE TABLE IF NOT EXISTS `mind` (
  `id`          BIGINT(19) NOT NULL,
  `owner_token` VARCHAR(255) NOT NULL,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `thought` (
  `id`          BIGINT(19) NOT NULL,
  `body`        VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `kind`        VARCHAR(100) NOT NULL,
  `public`      TINYINT(1) DEFAULT 0 NOT NULL,
  `mind_id`     INT NOT NULL,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX m_ind (mind_id),
  FOREIGN KEY (mind_id) REFERENCES mind(id)
) ENGINE=INNODB;